# -*- MakeFile -*-
# 
# unit test for logging subsystem
#

objects := dmalloc_log.o dmalloc_common.o
depends := $(objects:.o=.d)
target  := ut-logs

uname := $(shell uname -s)
ifeq ($(uname), Linux)
	os = LINUX
endif
ifeq ($(uname), Darwin)
	os = DARWIN
endif

%.o: %.c
	gcc -g -std=c99 -Wall -Wextra -D DMALLOC_UNIT_TEST -D $(os) -c  $<  -o $@
	@gcc -MM $*.c > $*.d

$(target): $(objects)
	gcc -g  $^  -o $@	

clean:
	rm -f *.o *.d *~ $(target)

-include $(depends)
