# -*- MakeFile -*-
# 
# unit test for stat and logging subsystem
#

objects := dmalloc_stats.o dmalloc_common.o dmalloc_log.o
depends := $(objects:.o=.d)

uname := $(shell uname -s)
ifeq ($(uname), Linux)
	os = LINUX
endif
ifeq ($(uname), Darwin)
	os = DARWIN
endif

%.o: %.c
	gcc -g -std=c99 -Wall -Wextra -D DMALLOC_STATS_UNIT -D $(os) -c  $<  -o $@
	@gcc -MM $*.c > $*.d

unit: $(objects)
	gcc -g  $^  -o $@	

clean:
	rm -f *.o *.d *~ unit

-include $(depends)
